### ISSUE TITLE
Autocompleting an import in Typescript adds the import twice

### ISSUE THREAD

**Issue by iamnbutler** [zed-industries/feedback#71]
**Describe the bug**

Using autocomplete to complete an import doubles the current import.

<img width="805" alt="CleanShot - 2022-06-14 at 11 25 06@2x" src="https://user-images.githubusercontent.com/1714999/173616250-0c95c2c9-c104-45f6-8663-a0cf76fe2379.png">

<img width="849" alt="CleanShot - 2022-06-14 at 11 25 15@2x" src="https://user-images.githubusercontent.com/1714999/173616291-53ab4214-3ada-49ae-87f4-419699b1fe89.png">

**Comment by iamnbutler** [comment]
I *think* this is fixed, I haven't had this issue in a while. Please let me know if you all experience this again!

**Comment by s-h-o-t** [comment]
I'm still experiencing this on `0.50.0`

**Comment by jmegs** [comment]
raising my hand to say still experiencing this on `0.62.4`

**Comment by iamnbutler** [comment]
Oh hmm.. I haven't experienced this in quite a while and write TS almost daily in Zed 🤔 wonder what the difference is...

**Comment by hovsater** [comment]
This is definitely a problem still. I'm on a brand new project and this is what I see.


https://user-images.githubusercontent.com/503025/199971282-b7c695b2-9ab9-447d-918a-7eafecc3bcff.mov

I'm running [Node](https://nodejs.org/en/), version `18.12.0` and [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server), version `2.1.0`.

**Comment by ForLoveOfCats** [comment]
After some experimentation I can reproduce, the issue only seems to be present in .js files not .ts files which explains why only some people are seeing it. I'm looking more into it, thanks for your patience in bringing this back up!

**Comment by JosephTLyons** [comment]
> After some experimentation I can reproduce, the issue only seems to be present in .js files not .ts files which explains why only some people are seeing it. I'm looking more into it, thanks for your patience in bringing this back up!

Ah yeah, that would explain why I never see it - we aren't in js a lot of the time.
